version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=sgw-backend
      # - discovery.seed_hosts=es02,es03
      - discovery.seed_hosts=es01
      # - cluster.initial_master_nodes=es01,es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      sgw-backend:
        ipv4_address: 172.16.239.2
        
  # es02:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
  #   container_name: es02
  #   environment:
  #     - node.name=es02
  #     - cluster.name=sgw-backend
  #     - discovery.seed_hosts=es01,es03
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data02:/usr/share/elasticsearch/data
  #   ports:
  #     - 9202:9200  
  #   networks:
  #     sgw-backend:
  #       ipv4_address: 172.16.239.3
  # es03:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
  #   container_name: es03
  #   environment:
  #     - node.name=es03
  #     - cluster.name=sgw-backend
  #     - discovery.seed_hosts=es01,es02
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data03:/usr/share/elasticsearch/data
  #   ports:
  #     - 9203:9200  
  #   networks:
  #     sgw-backend:
  #       ipv4_address: 172.16.239.4
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.15.1
  #   container_name: kibana
  #   environment:
  #     - SERVER_NAME=kibana
  #     - ELASTICSEARCH_HOSTS=http://172.16.239.10:9200
  #     - MONITORING_ENABLED=false
  #   ports:
  #     - 5601:5601
  #   networks:
  #     elastic:
  #       ipv4_address: 172.16.239.5

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  sgw-backend:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1
