version: '3'
services:
  es01:
    image: "docker.io/registry:latest"
    container_name: registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE: /certs/{{ registry_httpTlsCert }}
      - REGISTRY_HTTP_TLS_KEY: /certs/{{ registry_httpTlsKey }}
      # - REGISTRY_AUTH: htpasswd
      # - REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      # - REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm      
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 443:443
    networks:
      sgw-backend:
        ipv4_address: 172.16.240.2


volumes:
  data01:
    driver: local

networks:
  sgw-backend:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.240.0/24
          gateway: 172.16.240.1
